version: "3.8"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app/server
      - ./cairo:/app/cairo
    environment:
      - PATH=/root/.local/bin:${PATH}
    tty: true
